spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
  flyway:
    schemas:
      - public
      - library
  jpa:
    show-sql: true
server:
  port: 8081
logging:
  level:
    sql: info